name: 'AnnotateRunApi'
description: 'This is a thin layer to route messages to the overview of a github action run'
author: 'mholetzko'
inputs:
  warning: # change this
    required: false
    description: 'This message - if set - will be printed as warning to the action(s) summary'
  info: # change this
    required: false
    description: 'This message - if set - will be printed as info to the action(s) summary'
  error: # change this
    required: false
    description: 'This message - if set - will be printed as error to the action(s) summary'
runs:
  using: 'node12'
  main: 'dist/index.js'
